/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import ServiceCard from "./ServiceCard";

const ServicesSection = () => {
  const services = [
    {
      icon: "chart-line",
      title: "Advanced Analytics",
      description:
        "Gain insights with our cutting-edge analytical tools and real-time market data.",
    },
    {
      icon: "robot",
      title: "Automated Trading",
      description:
        "Leverage AI-powered algorithms for efficient and strategic trading execution.",
    },
    {
      icon: "users",
      title: "Expert Mentorship",
      description:
        "Learn from industry professionals and refine your trading strategies.",
    },
    {
      icon: "shield-alt",
      title: "Risk Management",
      description:
        "Protect your investments with our advanced risk assessment and mitigation tools.",
    },
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  };

  return (
    <section id="services" className="py-16 bg-[#ecf0f1]">
      <div className="container mx-auto px-4">
        <motion.h2
          className="text-3xl font-bold text-center text-[#001f3f] mb-12"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          Our Services
        </motion.h2>
        <motion.div
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8"
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          {services.map((service, index) => (
            <ServiceCard key={index} {...service} />
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default ServicesSection;
