/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import BlogCard from "./BlogCard";
import CTAButton from '../common/CTAButton'
const BlogSection = () => {
  const blogPosts = [
    {
      title: "Understanding Market Trends",
      excerpt:
        "Learn how to identify and capitalize on emerging market trends.",
      date: "2023-05-15",
      author: "Jane Doe",
      image: "/images/market-trends.jpg",
    },
    {
      title: "Risk Management Strategies",
      excerpt:
        "Discover effective ways to mitigate risks in your trading portfolio.",
      date: "2023-05-10",
      author: "John Smith",
      image: "/images/risk-management.jpg",
    },
    {
      title: "The Impact of AI on Trading",
      excerpt:
        "Explore how artificial intelligence is revolutionizing the trading industry.",
      date: "2023-05-05",
      author: "Mike Johnson",
      image: "/images/ai-trading.jpg",
    },
  ];

  return (
    <section className="py-16 bg-[#ecf0f1]">
      <div className="container mx-auto px-4">
        <motion.h2
          className="text-3xl font-bold text-center text-[#001f3f] mb-12"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          Latest Insights
        </motion.h2>
        <motion.div
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          {blogPosts.map((post, index) => (
            <BlogCard key={index} {...post} />
          ))}
        </motion.div>
        <motion.div
          className="text-center mt-12"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          {/* <a
            href="/blog"
            className="inline-block px-6 py-3 bg-[#001f3f] text-[#ffffff] rounded-md hover:bg-[#2c3e50] transition-colors duration-200"
          >
            View All Posts
          </a> */}
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6, duration: 0.8 }}
          className="text-center mt-12"
        >
          <CTAButton onClick={() => console.log("Start Viewing All Posts")}>
            View All Posts
          </CTAButton>
        </motion.div>
      </div>
    </section>
  );
};

export default BlogSection;
