/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const BlogCard = ({ title, excerpt, date, author, image }) => {
  return (
    <motion.div
      className="bg-[#ffffff] rounded-lg shadow-md overflow-hidden"
      whileHover={{ y: -5, transition: { duration: 0.2 } }}
    >
      <img src={image} alt={title} className="w-full h-48 object-cover" />
      <div className="p-6">
        <h3 className="text-xl font-semibold text-[#001f3f] mb-2">{title}</h3>
        <p className="text-[#34495e] mb-4">{excerpt}</p>
        <div className="flex justify-between items-center text-sm text-[#34495e]">
          <span>{author}</span>
          <span>{new Date(date).toLocaleDateString()}</span>
        </div>
      </div>
    </motion.div>
  );
};

export default BlogCard;
