/**
 * This code was generated by Builder.io.
 */
import React from "react";
import WhyChooseUsCard from "./WhyChooseUsCard";

const WhyChooseUsSection = () => {
  const features = [
    {
      id:'21wq',
      icon: "chart-line",
      title: "Advanced Resources",
      description:
        "Access to advanced trading resources.",
    },
    {
      id:'21eq',
      icon: "money",
      title: "Financial Support",
      description:
        "Financial support for your trading activities.",
    },
    {
      id:'21xq',
      icon: "users",
      title: "Networking Opportunities",
      description:
        "Join a network of professional traders and share strategies.",
    },
    {
      id:'21cv',
      icon: "check-circle",
      title: "Zero Cost",
      description: "No application fee - it's a risk-free opportunity.",
    },
  ];

  return (
    <section className="py-16 bg-gray-100">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-[#001f3f] mb-12">
          Why You Should Apply
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature) => (
            <WhyChooseUsCard key={feature.id} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default WhyChooseUsSection;
