/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import TestimonialCard from "./TestimonialCard";

const TestimonialsSection = () => {
  const testimonials = [
    {
      name: "John Doe",
      position: "Professional Trader",
      quote:
        "FinTrade has revolutionized my trading strategy. The advanced analytics are unparalleled.",
      rating: 5,
    },
    {
      name: "Jane Smith",
      position: "Investment Analyst",
      quote:
        "The expert mentorship program provided invaluable insights for my career growth.",
      rating: 5,
    },
    {
      name: "Mike Johnson",
      position: "Hedge Fund Manager",
      quote:
        "FinTrade's risk management tools have significantly improved our portfolio performance.",
      rating: 4,
    },
  ];

  return (
    <section className="py-16 bg-[#ffffff]">
      <div className="container mx-auto px-4">
        <motion.h2
          className="text-3xl font-bold text-center text-[#001f3f] mb-12"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          What Our Clients Say
        </motion.h2>
        <motion.div className="flex flex-col md:flex-row justify-center items-center space-y-8 md:space-y-0 md:space-x-8">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard key={index} {...testimonial} />
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
