/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faStar } from "@fortawesome/free-solid-svg-icons";

const TestimonialCard = ({ name, position, quote, rating }) => {
  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  };

  return (
    <motion.div
      className="bg-[#ffffff] p-6 rounded-lg shadow-md max-w-md"
      variants={cardVariants}
      initial="hidden"
      animate="visible"
      transition={{ duration: 0.5 }}
    >
      <p className="text-[#34495e] mb-4 italic">"{quote}"</p>
      <div className="flex items-center justify-between">
        <div>
          <h4 className="text-[#f1c40f] font-semibold">{name}</h4>
          <p className="text-[#34495e] text-sm">{position}</p>
        </div>
        <div className="flex">
          {[...Array(5)].map((_, i) => (
            <FontAwesomeIcon
              key={i}
              icon={faStar}
              className={i < rating ? "text-[#f1c40f]" : "text-[#ecf0f1]"}
            />
          ))}
        </div>
      </div>
    </motion.div>
  );
};

export default TestimonialCard;
